
-- TẠO CSDL 
CREATE DATABASE QuanLyBanHang;
GO

USE QuanLyBanHang;
GO

-- Tạo bảng KHACHHANG

CREATE TABLE KHACHHANG (
	MAKH CHAR(4) PRIMARY KEY ,
	HOTEN VARCHAR(40),
	DCHI VARCHAR(50),
	SODT VARCHAR(20),
	NGSINH SMALLDATETIME,
	NGDK SMALLDATETIME,
	DOANHSO MONEY
);

GO

-- TẠO BẢNG NHANVIEN

CREATE TABLE NHANVIEN(
	MANV CHAR(4) PRIMARY KEY ,
	HOTEN VARCHAR(40),
	SODT VARCHAR(20),
	NGVL SMALLDATETIME
);

GO

-- TẠO BẢNG SANPHAM	

CREATE TABLE SANPHAM(
	MASP CHAR(4) PRIMARY KEY,
	TENSP VARCHAR(40), 
	DVT VARCHAR(20), 
	NUOCSX VARCHAR(40), 
	GIA MONEY
);

GO

-- TẠO BẢNG HOADON

CREATE TABLE HOADON(
	SOHD INT PRIMARY KEY, 
	NGHD SMALLDATETIME, 
	MAKH CHAR(4),
	MANV CHAR(4),
	CONSTRAINT FK_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH), 
	CONSTRAINT FK_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV), 
	TRIGIA MONEY
);

GO

-- TẠO BẢNG CTHD

CREATE TABLE CTHD(
	SOHD INT,
	MASP CHAR(4),
	SL INT, 
	PRIMARY KEY(SOHD, MASP),
	CONSTRAINT FK_CTHD_SOHD FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
    CONSTRAINT FK_CTHD_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);

GO

-- TẠO CSDL QuanLyGiaoVu
CREATE DATABASE QuanLyGiaoVu;
GO

USE QuanLyGiaoVu;

GO

-- Tạo bảng KHOA
CREATE TABLE KHOA(
	MAKHOA VARCHAR(4) PRIMARY KEY,
	TENKHOA VARCHAR(40),
	NGTLAP SMALLDATETIME,
	TRGKHOA CHAR(4)
);
GO

-- Tạo bảng MONHOC
CREATE TABLE MONHOC(
	MAMH VARCHAR(10) PRIMARY KEY,
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA VARCHAR(4)
);
GO

-- Tạo bảng DIEUKIEN
CREATE TABLE DIEUKIEN(
	MAMH VARCHAR(10),
	MAMH_TRUOC VARCHAR(10),
	PRIMARY KEY(MAMH, MAMH_TRUOC)
);
GO

-- Tạo bảng GIAOVIEN
CREATE TABLE GIAOVIEN(
	MAGV CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GIOITINH VARCHAR(3),
	NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME,
	HESO NUMERIC(4,2),
	MUCLUONG MONEY,
	MAKHOA VARCHAR(4)
);
GO

-- Tạo bảng LOP
CREATE TABLE LOP(
	MALOP CHAR(3) PRIMARY KEY,
	TENLOP VARCHAR(40),
	TRGLOP CHAR(5),
	SISO TINYINT,
	MAGVCN CHAR(4)
);
GO

-- Tạo bảng HOCVIEN
CREATE TABLE HOCVIEN(
	MAHV CHAR(5) PRIMARY KEY,
	HO VARCHAR(40),
	TEN VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	NOISINH VARCHAR(40),
	MALOP CHAR(3)
);
GO

-- Tạo bảng GIANGDAY
CREATE TABLE GIANGDAY(
	MALOP CHAR(3),
	MAMH VARCHAR(10),
	MAGV CHAR(4),
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME,
	PRIMARY KEY(MALOP, MAMH)
);
GO

-- Tạo bảng KETQUATHI
CREATE TABLE KETQUATHI(
	MAHV CHAR(5),
	MAMH VARCHAR(10),
	LANTHI TINYINT,
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KQUA VARCHAR(10),
	PRIMARY KEY(MAHV, MAMH, LANTHI)
);
GO

-- THÊM KHÓA NGOẠI

ALTER TABLE MONHOC
ADD CONSTRAINT FK_MONHOC_MAKHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);
GO

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DIEUKIEN_MAMH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
    CONSTRAINT FK_DIEUKIEN_MAMH_TRUOC FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH);
GO

ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GIAOVIEN_MAKHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);
GO

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_TRGLOP FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN(MAHV),
    CONSTRAINT FK_LOP_MAGVCN FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV);
GO

ALTER TABLE HOCVIEN
ADD CONSTRAINT FK_HOCVIEN_MALOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);
GO

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GIANGDAY_MALOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP),
    CONSTRAINT FK_GIANGDAY_MAMH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
    CONSTRAINT FK_GIANGDAY_MAGV FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV);
GO

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KETQUATHI_MAHV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV),
    CONSTRAINT FK_KETQUATHI_MAMH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);
GO

-- Thêm vào 3 thuộc tính GHICHU, DIEMTB, XEPLOAI cho quan hệ HOCVIEN.

ALTER TABLE HOCVIEN

ADD  GHICHU VARCHAR(255), DIEMTB NUMERIC , XEPLOAI VARCHAR(20);

GO

-- BÀI TẬP 2
-- Thêm vào thuộc tính GHICHU có kiểu dữ liệu varchar(20) cho quan hệ SANPHAM.

ALTER TABLE SANPHAM
ADD GHICHU VARCHAR(20);

GO


-- Thêm vào thuộc tính LOAIKH có kiểu dữ liệu là tinyint cho quan hệ KHACHHANG.

ALTER TABLE KHACHHANG
ADD LOAIKH TINYINT;

GO

-- Sửa kiểu dữ liệu của thuộc tính GHICHU trong quan hệ SANPHAM thành varchar(100)

ALTER TABLE SANPHAM
ALTER COLUMN GHICHU VARCHAR(100);

GO

-- Xóa thuộc tính GHICHU trong quan hệ SANPHAM.

ALTER TABLE SANPHAM
DROP COLUMN GHICHU;

GO

-- Làm thế nào để thuộc tính LOAIKH trong quan hệ KHACHHANG có thể lưu các giá trị là: “Vang lai”, “Thuong xuyen”, “Vip”…

CREATE TABLE LOAIKHACHHANG ( 
	MALOAI TINYINT PRIMARY KEY, 
	TENLOAI NVARCHAR(20) NOT NULL 
); --Tạo bảng để define loaikh

GO

ALTER TABLE KHACHHANG
ADD CONSTRAINT FK_KHACHHANG_LOAIKH
FOREIGN KEY (LOAIKH)
REFERENCES LOAIKHACHHANG(MALOAI);

GO 

INSERT INTO LOAIKHACHHANG(MALOAI, TENLOAI)
VALUES
(0, 'Vang lai'), 
(1, 'Thuong xuyen'), 
(2, 'Vip');

GO


-- Đơn vị tính của sản phẩm chỉ có thể là (“cay”,”hop”,”cai”,”quyen”,”chuc”)
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_SANPHAM_DVT
CHECK (DVT IN ('cay','hop','cai','quyen','chuc'));
GO

-- Giá bán của sản phẩm từ 500 đồng trở lên.

ALTER TABLE SANPHAM
ADD CONSTRAINT CK_SANPHAM_GIA
CHECK (GIA >= 500);

GO

-- Mỗi lần mua hàng, khách hàng phải mua ít nhất 1 sản phẩm.

ALTER TABLE CTHD
ADD CONSTRAINT CK_CTHD_SL 
CHECK (SL >=1);

GO

-- Ngày khách hàng đăng ký là khách hàng thành viên phải lớn hơn ngày sinh của người đó.

ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_KHACHHANG_NGAYDK
CHECK (NGDK > NGSINH);

GO


-- BÀI TẬP 3

-- * Mã học viên là một chuỗi 5 ký tự, 3 ký tự đầu là mã lớp, 2 ký tự cuối cùng là số thứ tự học viên trong lớp. VD: “K1101”

ALTER TABLE HOCVIEN
ADD CONSTRAINT CK_HOCVIEN_MAHV_FORMAT
CHECK (
	LEN(MAHV)=5
	AND ISNUMERIC(RIGHT(MAHV,2))=1
);

GO

-- Thuộc tính GIOITINH chỉ có giá trị là “Nam” hoặc “Nu”.

ALTER TABLE HOCVIEN
ADD CONSTRAINT CK_HOCVIEN_GTINH
CHECK (GIOITINH IN ('Nam','Nu'));

GO


-- Điểm số của một lần thi có giá trị từ 0 đến 10 và cần lưu đến 2 số lẽ (VD: 6.22).

ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_KETQUATHI_DIEM
CHECK(
	DIEM BETWEEN 0 AND 10
);

GO

ALTER TABLE KETQUATHI
ALTER COLUMN DIEM NUMERIC(2,2);

GO

-- Kết quả thi là “Dat” nếu điểm từ 5 đến 10  và “Khong dat” nếu điểm nhỏ hơn 5.
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_KETQUATHI_KQUA
CHECK (
	(DIEM BETWEEN 5 AND 10 AND KQUA='Dat')
	OR (DIEM < 5 AND KQUA='Khong dat')
);

GO

-- Học viên thi một môn tối đa 3 lần.
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_KETQUATHI_LANTHI
CHECK(
	LANTHI <4
);

GO

-- Học kỳ chỉ có giá trị từ 1 đến 3.
ALTER TABLE GIANGDAY
ADD CONSTRAINT CK_GIANGDAY_HOCKY
CHECK (
	HOCKY BETWEEN 1 AND 3
);
GO

-- Học vị của giáo viên chỉ có thể là “CN”, “KS”, “Ths”, ”TS”, ”PTS”

	ALTER TABLE GIAOVIEN
	ADD CONSTRAINT CK_GIAOVIEN_HOCVI
	CHECK(
		HOCVI IN (N'CN', N'KS', N'Ths', N'TS', N'PTS')
	);
	GO