CREATE DATABASE QuanLyBanHang;
GO

USE QuanLyBanHang;
GO

CREATE TABLE KHACHHANG(
	MAKH CHAR(4) NOT NULL PRIMARY KEY,
	HOTEN VARCHAR(40),
	DCHI VARCHAR(50),
	SODT VARCHAR(20),
	NGSINH SMALLDATETIME,
	NGDK SMALLDATETIME,
	DOANHSO MONEY
);
GO

CREATE TABLE NHANVIEN(
	MANV CHAR(4) NOT NULL PRIMARY KEY,
	HOTEN VARCHAR(40),
	SODT VARCHAR(20),
	NGVL SMALLDATETIME
);
GO

CREATE TABLE SANPHAM(
	MASP CHAR(4) NOT NULL PRIMARY KEY,
	TENSP VARCHAR(40),
	DVT VARCHAR(20),
	NUOCSX VARCHAR(40),
	GIA MONEY
);
GO

CREATE TABLE HOADON(
	SOHD INT NOT NULL PRIMARY KEY,
	NGHD SMALLDATETIME,
	MAKH CHAR(4),
	MANV CHAR(4) NOT NULL,
	TRIGIA MONEY
);
GO

CREATE TABLE CTHD(
	SOHD INT NOT NULL,
	MASP CHAR(4) NOT NULL,
	SL INT,
	PRIMARY KEY (SOHD, MASP)
);
GO

ALTER TABLE HOADON
ADD CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH);
GO

ALTER TABLE HOADON
ADD CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);
GO

ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_HD FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD);
GO

ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP);
GO

ALTER TABLE SANPHAM
ADD GHICHU VARCHAR(20);
GO

ALTER TABLE KHACHHANG
ADD LOAIKH TINYINT;
GO

ALTER TABLE SANPHAM
ALTER COLUMN GHICHU VARCHAR(100);
GO

ALTER TABLE SANPHAM
DROP COLUMN GHICHU;
GO

ALTER TABLE KHACHHANG
ALTER COLUMN LOAIKH VARCHAR(20);
GO

ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_KH_LOAIKH CHECK (LOAIKH IN ('Vang lai', 'Thuong xuyen', 'Vip'));
GO

ALTER TABLE SANPHAM
ADD CONSTRAINT CK_SP_DVT CHECK (DVT IN ('cay','hop','cai','quyen','chuc'));
GO

ALTER TABLE SANPHAM
ADD CONSTRAINT CK_SP_TRIGIA CHECK (GIA >= 500);
GO

ALTER TABLE CTHD
ADD CONSTRAINT CK_CTHD_SL CHECK (SL >=1);
GO

ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_KH_NGDK CHECK (NGDK > NGSINH);
GO

CREATE DATABASE QuanLyGiaoVu;
GO

USE QuanLyGiaoVu;
GO

CREATE TABLE KHOA (
	MAKHOA VARCHAR(4) NOT NULL PRIMARY KEY,
	TENKHOA VARCHAR(40),
	NGTLAP SMALLDATETIME,
	TRGKHOA CHAR(4)
);
GO

CREATE TABLE GIAOVIEN (
	MAGV CHAR(4) NOT NULL PRIMARY KEY,
	HOTEN VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GIOITINH VARCHAR(3),
	NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME,
	HESO NUMERIC(4,2),
	MUCLUONG MONEY,
	MAKHOA VARCHAR(4)
);
GO

CREATE TABLE LOP (
	MALOP CHAR(3) NOT NULL PRIMARY KEY,
	TENLOP VARCHAR(40),
	TRGLOP CHAR(5),
	SISO TINYINT,
	MAGVCN CHAR(4)
);
GO

CREATE TABLE HOCVIEN (
	MAHV CHAR(5) NOT NULL PRIMARY KEY,
	HO VARCHAR(40),
	TEN VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	NOISINH VARCHAR(40),
	MALOP CHAR(3)
);
GO

CREATE TABLE MONHOC (
	MAMH VARCHAR(10) NOT NULL PRIMARY KEY,
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA VARCHAR(4)
);
GO

CREATE TABLE DIEUKIEN (
	MAMH VARCHAR(10) NOT NULL,
	MAMH_TRUOC VARCHAR(10) NOT NULL,
	PRIMARY KEY (MAMH, MAMH_TRUOC)
);
GO

CREATE TABLE GIANGDAY (
	MALOP CHAR(3) NOT NULL,
	MAMH VARCHAR(10) NOT NULL,
	MAGV CHAR(4),
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME,
	PRIMARY KEY (MALOP, MAMH)
);
GO

CREATE TABLE KETQUATHI (
	MAHV CHAR(5) NOT NULL,
	MAMH VARCHAR(10) NOT NULL,
	LANTHI TINYINT NOT NULL,
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KQUA VARCHAR(10),
	PRIMARY KEY (MAHV, MAMH, LANTHI)
);
GO

ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GV_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);
GO

ALTER TABLE KHOA
ADD CONSTRAINT FK_KHOA_GV FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV);
GO

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_GV FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV);
GO

ALTER TABLE HOCVIEN
ADD CONSTRAINT FK_HV_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);
GO

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_HV FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN(MAHV);
GO

ALTER TABLE MONHOC
ADD CONSTRAINT FK_MH_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);
GO

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DK_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);
GO

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DK_MHT FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH);
GO

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GD_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);
GO

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GD_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);
GO

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GD_GV FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV);
GO

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KQ_HV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV);
GO

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KQ_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);
GO

ALTER TABLE HOCVIEN
ADD CONSTRAINT CK_GT_HV CHECK (GIOITINH IN ('Nam','Nu'));
GO

ALTER TABLE GIAOVIEN
ADD CONSTRAINT CK_GT_GV CHECK (GIOITINH IN ('Nam','Nu'));
GO

ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_DIEM CHECK (DIEM >=0 AND DIEM <=10);
GO

ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_KQ_DIEM
CHECK (
	(DIEM >= 5 AND KQUA = N'Dat') OR
	(DIEM < 5 AND KQUA = N'Khong dat')
);
GO

ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_LANTHI CHECK (LANTHI >= 1 AND LANTHI <=3);
GO

ALTER TABLE GIANGDAY
ADD CONSTRAINT CK_HOCKY CHECK (HOCKY >=1 AND HOCKY <=3);
GO

ALTER TABLE GIAOVIEN
ADD CONSTRAINT CK_GV_HOCVI
CHECK (HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'));
GO