 CREATE DATABASE QuanLyBanHang;
 GO

 USE QuanLyBanHang;
 GO

 CREATE TABLE KHACHHANG(
	MAKH CHAR(4),
	HOTEN VARCHAR(40),
	DCHI VARCHAR(50),
	SODT VARCHAR(20),
	NGSINH SMALLDATETIME,
	NGDK SMALLDATETIME,
	DOANHSO MONEY
 );

ALTER TABLE KHACHHANG
ALTER COLUMN MAKH CHAR(4) NOT NULL;
GO

 ALTER TABLE KHACHHANG
 ADD CONSTRAINT PK_KH PRIMARY KEY (MAKH);
 GO

 CREATE TABLE NHANVIEN(
	MANV CHAR(4) NOT NULL,
	HOTEN VARCHAR(40),
	SODT VARCHAR(20),
	NGVL SMALLDATETIME
 )
 GO

 ALTER TABLE NHANVIEN
 ADD CONSTRAINT PK_NV PRIMARY KEY (MANV);
 GO

 CREATE TABLE SANPHAM(
	MASP CHAR(4) NOT NULL,
	TENSP VARCHAR(40),
	DVT VARCHAR(20),
	NUOCSX VARCHAR(40),
	GIA MONEY
 )
 GO

 ALTER TABLE SANPHAM 
 ADD CONSTRAINT PK_SP PRIMARY KEY (MASP);
 GO

 CREATE TABLE HOADON(
	SOHD INT,
	NGHD SMALLDATETIME,
	MAKH CHAR(4) NOT NULL,
	MANV CHAR(4) NOT NULL,
	TRIGIA MONEY
 )
GO

ALTER TABLE HOADON
ALTER COLUMN SOHD INT NOT NULL;
GO

ALTER TABLE HOADON
ADD CONSTRAINT PK_HD PRIMARY KEY (SOHD);
GO


ALTER TABLE HOADON
ADD CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);
GO

CREATE TABLE CTHD(
	SOHD INT,
	MASP CHAR(4) NOT NULL,
	SL INT
)
GO

ALTER TABLE CTHD
ALTER COLUMN SOHD INT NOT NULL;
GO
ALTER TABLE CTHD
ADD CONSTRAINT PK_CTHD PRIMARY KEY (SOHD,MASP);
ALTER TABLE CTHD 
ADD CONSTRAINT FK_CTHD_HD FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD);

ALTER TABLE CTHD 
ADD CONSTRAINT FK_CTHD_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP);
GO

-- QUẢN LÍ BÁN HÀNG 2-10
--2
ALTER TABLE SANPHAM
ADD GHICHU VARCHAR(20);
GO
--3
ALTER TABLE KHACHHANG
ADD LOAIKH TINYINT;
GO
--4
ALTER TABLE SANPHAM
ALTER COLUMN GHICHU VARCHAR(100);
GO
--5
ALTER TABLE SANPHAM
DROP COLUMN GHICHU;
GO
--6
ALTER TABLE KHACHHANG
ALTER COLUMN LOAIKH VARCHAR(20);
GO

ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_KH_LOAIKH CHECK (LOAIKH IN ('Vang lai', 'Thuong xuyen', 'Vip'));
GO
--7
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_SP_DVT CHECK (DVT IN ('cay','hop','cai','quyen','chuc'));
GO
--8
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_SP_TRIGIA CHECK (GIA >= 500);
GO
--9
ALTER TABLE CTHD
ADD CONSTRAINT CK_CTHD_SL CHECK (SL >=1);
GO
--10
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_KH_NGDK CHECK (NGDK > NGSINH);
GO
--QuanLyGiaoVu
CREATE DATABASE QuanLyGiaoVu;
GO

USE QuanLyGiaoVu;
GO

CREATE TABLE KHOA (
    MAKHOA VARCHAR(4),
    TENKHOA VARCHAR(40),
    NGTLAP SMALLDATETIME,
    TRGKHOA CHAR(4)
);
GO

CREATE TABLE MONHOC (
    MAMH VARCHAR(10),
    TENMH VARCHAR(40),
    TCLT TINYINT,
    TCTH TINYINT,
    MAKHOA VARCHAR(4)
);
GO

CREATE TABLE DIEUKIEN (
    MAMH VARCHAR(10),
    MAMH_TRUOC VARCHAR(10)
);
GO

CREATE TABLE GIAOVIEN (
    MAGV CHAR(4),
    HOTEN VARCHAR(40),
    HOCVI VARCHAR(10),
    HOCHAM VARCHAR(10),
    GIOITINH VARCHAR(3),
    NGSINH SMALLDATETIME,
    NGVL SMALLDATETIME,
    HESO NUMERIC(4,2),
    MUCLUONG MONEY,
    MAKHOA VARCHAR(4)
);
GO

CREATE TABLE LOP (
    MALOP CHAR(3),
    TENLOP VARCHAR(40),
    TRGLOP CHAR(5),
    SISO TINYINT,
    MAGVCN CHAR(4)
);
GO

CREATE TABLE HOCVIEN (
    MAHV CHAR(5),
    HO VARCHAR(40),
    TEN VARCHAR(10),
    NGSINH SMALLDATETIME,
    GIOITINH VARCHAR(3),
    NOISINH VARCHAR(40),
    MALOP CHAR(3)
);
GO

CREATE TABLE GIANGDAY (
    MALOP CHAR(3),
    MAMH VARCHAR(10),
    MAGV CHAR(4),
    HOCKY TINYINT,
    NAM SMALLINT,
    TUNGAY SMALLDATETIME,
    DENNGAY SMALLDATETIME
);
GO

CREATE TABLE KETQUATHI (
    MAHV CHAR(5),
    MAMH VARCHAR(10),
    LANTHI TINYINT,
    NGTHI SMALLDATETIME,
    DIEM NUMERIC(4,2),
    KQUA VARCHAR(10)
);
GO

-- THÊM KHÓA
ALTER TABLE HOCVIEN
ADD CONSTRAINT PK_HV PRIMARY KEY (MAHV);
GO

ALTER TABLE HOCVIEN
ADD CONSTRAINT FK_HV_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);
GO

ALTER TABLE LOP
ADD CONSTRAINT PK_LOP PRIMARY KEY (MALOP);
GO

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_GV FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV);
GO

ALTER TABLE KHOA
ADD CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA);
GO

ALTER TABLE MONHOC 
ADD CONSTRAINT PK_MH PRIMARY KEY (MAMH);
ALTER TABLE MONHOC
ADD CONSTRAINT FK_MH_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);
GO

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DK_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DK_MHT FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH);

ALTER TABLE DIEUKIEN 
ADD CONSTRAINT PK_DK PRIMARY KEY (MAMH, MAMH_TRUOC);
GO

ALTER TABLE GIAOVIEN
ADD CONSTRAINT PK_GV PRIMARY KEY (MAGV);

ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GV_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);

GO

ALTER TABLE GIANGDAY
ADD CONSTRAINT PK_GD PRIMARY KEY (MALOP, MAMH);

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GD_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GD_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GD_GV FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV);
GO


ALTER TABLE KETQUATHI
ADD CONSTRAINT PK_KQ PRIMARY KEY (MAHV, MAMH, LANTHI);
GO

ALTER TABLE KETQUATHI 
ADD CONSTRAINT FK_KQ_HV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV);

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KQ_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);
GO

-- BÀI 3-9
--3
ALTER TABLE HOCVIEN
ADD CONSTRAINT CK_GT_HV CHECK (GIOITINH IN ('Nam','Nu')); 

ALTER TABLE GIAOVIEN
ADD CONSTRAINT CK_GT_GV CHECK (GIOITINH IN ('Nam','Nu')); 

GO
--4
ALTER TABLE KETQUATHI
ALTER COLUMN DIEM DECIMAL(4,2);

ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_DIEM CHECK (DIEM >=0 AND DIEM <=10);
GO
--5
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_KQ_DIEM
CHECK (
    (DIEM >= 5 AND KQUA = N'Dat') OR
    (DIEM < 5 AND KQUA = N'Khong dat')
);
GO
--6
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_LANTHI CHECK (LANTHI >=0 AND LANTHI <=3);
GO
--7
ALTER TABLE GIANGDAY
ADD CONSTRAINT CK_HOCKY CHECK (HOCKY >=1 AND HOCKY <=3);
GO
--8
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CK_GV_HOCVI 
CHECK (HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'));
GO

